### ISSUE TITLE
Proposing a new section - WordPress Libraries.

### ISSUE THREAD

**Issue by atanas-dev** [lukecav/awesome-wp-developer-tools#22]
The current most-fitting section is specifically for APIs so libraries which do not interface with an API do not really fit. Add-ons that would fit in this new section would generally be installable though means such as Composer, for example.

A couple of examples:
- [WP Emerge](https://github.com/htmlburger/wpemerge) - this is the framework that I wanted to propose in a PR which is why I'm submitting this issue (if this section gets added I will submit a PR).
- [Controller](https://github.com/soberwp/controller)
- [Cortex](https://github.com/Brain-WP/Cortex)

If needed, I can submit a PR to add this section but wanted to raise it as a discussion first.

**Comment by lukecav** [comment]
That would be great.

**Comment by lukecav** [comment]
https://github.com/lukecav/awesome-wp-developer-tools#wordpress-libraries
